# TODO implement quadlets
# TODO drop cap
# TODO read only
# TODO etc.





services:
  app:
    image: llm-agent:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    pull_policy: never
    expose:
      - "0.0.0.0:3075"
    env_file:
      - .env
    volumes:
      - pds-llm-agent-data:/app/data

  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  pds-llm-agent-data:
    external: true
